# Generated by Django 5.1.6 on 2026-06-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_supplier_company_name_alter_supplier_phone'),
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteintake',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.supplier'),
        ),
        migrations.AlterField(
            model_name='wastepurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
