# Generated by Django 5.1.6 on 2026-06-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteintake',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
    ]
