# Generated by Django 5.1.6 on 2026-07-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_alter_wasteintake_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastepurchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wastepurchase',
            name='pieces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wastepurchase',
            name='timber_length',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wastepurchase',
            name='timber_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wastepurchase',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
