# Generated by Django 5.1.6 on 2026-06-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_wasteintake_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_management.wasteintake')),
            ],
        ),
    ]
