# Generated by Django 5.1.6 on 2026-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_ip_address_auditlog_user_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='NONE', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
