# Generated by Django 5.1.6 on 2026-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_customerpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
