# Generated by Django 5.1.6 on 2026-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
